"""
Standard Supply Catalog for Polar / Antarctic Operations
Contains predefined common supplies grouped by standard categories.
"""

STANDARD_SUPPLY_CATALOG = [
    # Food & Water
    {
        "name": "Dehydrated Ration Packs",
        "category": "Food & Water",
        "unit": "Packs",
        "weight_kg_per_unit": 1.2,
        "volume_m3_per_unit": 0.003,
        "priority": "High",
        "priority_value": 50,
        "inventory_name": "Emergency Rations (MRE)",
        "inventory_unit": "Units",
        "default_daily_use": 3.0,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "Canned High-Calorie Food Supplies",
        "category": "Food & Water",
        "unit": "Cans",
        "weight_kg_per_unit": 0.45,
        "volume_m3_per_unit": 0.0005,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 2.5,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "Potable Water Containers (20L)",
        "category": "Food & Water",
        "unit": "Containers",
        "weight_kg_per_unit": 20.5,
        "volume_m3_per_unit": 0.025,
        "priority": "Critical",
        "priority_value": 1000,
        "inventory_name": "Drinking Water Canisters",
        "inventory_unit": "Litres",
        "inventory_units_per_cargo_unit": 20,
        "default_daily_use": 0.5,
        "cold_sensitivity": 1.5,
    },
    {
        "name": "Emergency Energy Bars",
        "category": "Food & Water",
        "unit": "Boxes",
        "weight_kg_per_unit": 0.5,
        "volume_m3_per_unit": 0.002,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.2,
        "cold_sensitivity": 1.0,
    },

    # Fuel & Energy
    {
        "name": "Polar-Grade Jet-A1 Aviation Fuel",
        "category": "Fuel & Energy",
        "unit": "Litres",
        "weight_kg_per_unit": 0.8,
        "volume_m3_per_unit": 0.0011,
        "priority": "High",
        "priority_value": 50,
        "inventory_name": "Aviation Fuel (Jet-A1)",
        "default_daily_use": 20.0,
        "cold_sensitivity": 1.4,
    },
    {
        "name": "Sub-Zero Diesel Fuel (Special Additive)",
        "category": "Fuel & Energy",
        "unit": "Litres",
        "weight_kg_per_unit": 0.84,
        "volume_m3_per_unit": 0.0011,
        "priority": "High",
        "priority_value": 50,
        "inventory_name": "Diesel (Generator)",
        "default_daily_use": 25.0,
        "cold_sensitivity": 1.5,
    },
    {
        "name": "Propane Heating Gas Cylinders",
        "category": "Fuel & Energy",
        "unit": "Cylinders",
        "weight_kg_per_unit": 20.0,
        "volume_m3_per_unit": 0.1,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.5,
        "cold_sensitivity": 1.3,
    },

    # Medical
    {
        "name": "Extreme Cold First Aid & Frostbite Kit",
        "category": "Medical",
        "unit": "Kits",
        "weight_kg_per_unit": 2.0,
        "volume_m3_per_unit": 0.03,
        "priority": "Critical",
        "priority_value": 1000,
        "inventory_name": "Medical Kit (Field)",
        "inventory_unit": "Boxes",
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.2,
    },
    {
        "name": "Emergency Oxygen Cylinders",
        "category": "Medical",
        "unit": "Cylinders",
        "weight_kg_per_unit": 2.5,
        "volume_m3_per_unit": 0.04,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.02,
        "cold_sensitivity": 1.1,
    },
    {
        "name": "Trauma & Burn Surgical Supplies",
        "category": "Medical",
        "unit": "Kits",
        "weight_kg_per_unit": 5.0,
        "volume_m3_per_unit": 0.05,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.0,
    },

    # PPE/Clothing
    {
        "name": "Polar Thermal Parkas (-50C Rated)",
        "category": "PPE/Clothing",
        "unit": "Units",
        "weight_kg_per_unit": 1.5,
        "volume_m3_per_unit": 0.03,
        "priority": "Medium",
        "priority_value": 5,
        "inventory_name": "Thermal Gear Sets",
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "Insulated Insulated Boots & Thermal Socks",
        "category": "PPE/Clothing",
        "unit": "Pairs",
        "weight_kg_per_unit": 2.0,
        "volume_m3_per_unit": 0.02,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 0.02,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "UV-Protection Glacier Goggles",
        "category": "PPE/Clothing",
        "unit": "Units",
        "weight_kg_per_unit": 0.25,
        "volume_m3_per_unit": 0.002,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.0,
    },

    # Communication & Navigation
    {
        "name": "Iridium Extreme Satellite Phones",
        "category": "Communication & Navigation",
        "unit": "Units",
        "weight_kg_per_unit": 0.4,
        "volume_m3_per_unit": 0.003,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.5,
    },
    {
        "name": "Handheld VHF Radio Transceivers",
        "category": "Communication & Navigation",
        "unit": "Units",
        "weight_kg_per_unit": 0.3,
        "volume_m3_per_unit": 0.002,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.02,
        "cold_sensitivity": 1.4,
    },
    {
        "name": "Ruggedized GPS Navigation Units",
        "category": "Communication & Navigation",
        "unit": "Units",
        "weight_kg_per_unit": 0.25,
        "volume_m3_per_unit": 0.0015,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.02,
        "cold_sensitivity": 1.3,
    },

    # Tools & Maintenance
    {
        "name": "Vehicle Engine Anti-Freeze (-60C)",
        "category": "Tools & Maintenance",
        "unit": "Litres",
        "weight_kg_per_unit": 1.1,
        "volume_m3_per_unit": 0.0012,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 2.0,
        "cold_sensitivity": 1.5,
    },
    {
        "name": "Sno-Cat Track Repair Spares Kit",
        "category": "Tools & Maintenance",
        "unit": "Kits",
        "weight_kg_per_unit": 15.0,
        "volume_m3_per_unit": 0.08,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.2,
    },
    {
        "name": "Heavy Duty Snow Shovels & Ice Axes",
        "category": "Tools & Maintenance",
        "unit": "Units",
        "weight_kg_per_unit": 3.0,
        "volume_m3_per_unit": 0.025,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.0,
    },

    # Scientific Equipment
    {
        "name": "Ice Core Drilling Bits & Spares",
        "category": "Scientific Equipment",
        "unit": "Units",
        "weight_kg_per_unit": 8.0,
        "volume_m3_per_unit": 0.02,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.1,
        "cold_sensitivity": 1.1,
    },
    {
        "name": "Meteorological Sensor Probes",
        "category": "Scientific Equipment",
        "unit": "Units",
        "weight_kg_per_unit": 1.0,
        "volume_m3_per_unit": 0.005,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.3,
    },
    {
        "name": "Sample Cryo-Containers",
        "category": "Scientific Equipment",
        "unit": "Units",
        "weight_kg_per_unit": 0.5,
        "volume_m3_per_unit": 0.01,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.2,
        "cold_sensitivity": 1.2,
    },

    # Emergency & Survival
    {
        "name": "Polar Expedition Storm Tents (4-Person)",
        "category": "Emergency & Survival",
        "unit": "Units",
        "weight_kg_per_unit": 18.0,
        "volume_m3_per_unit": 0.12,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.1,
    },
    {
        "name": "Emergency Flares & Signal Smoke Kits",
        "category": "Emergency & Survival",
        "unit": "Kits",
        "weight_kg_per_unit": 4.0,
        "volume_m3_per_unit": 0.02,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "Emergency Blizzard Survival Bags",
        "category": "Emergency & Survival",
        "unit": "Units",
        "weight_kg_per_unit": 2.5,
        "volume_m3_per_unit": 0.03,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.02,
        "cold_sensitivity": 1.0,
    },

    # Hygiene & Sanitation
    {
        "name": "Biodegradable Sanitation Packs",
        "category": "Hygiene & Sanitation",
        "unit": "Packs",
        "weight_kg_per_unit": 0.8,
        "volume_m3_per_unit": 0.01,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 1.0,
        "cold_sensitivity": 1.0,
    },
    {
        "name": "Waterless Cleansing Wipes",
        "category": "Hygiene & Sanitation",
        "unit": "Packs",
        "weight_kg_per_unit": 0.4,
        "volume_m3_per_unit": 0.004,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 0.5,
        "cold_sensitivity": 1.1,
    },

    # Batteries/Power
    {
        "name": "LiFePO4 Low-Temp Solar Storage Batteries",
        "category": "Batteries/Power",
        "unit": "Units",
        "weight_kg_per_unit": 25.0,
        "volume_m3_per_unit": 0.15,
        "priority": "Critical",
        "priority_value": 1000,
        "default_daily_use": 0.05,
        "cold_sensitivity": 1.6,
    },
    {
        "name": "Heavy-Duty AA/AAA Cold-Resistant Lithium Batteries",
        "category": "Batteries/Power",
        "unit": "Packs",
        "weight_kg_per_unit": 0.5,
        "volume_m3_per_unit": 0.002,
        "priority": "Medium",
        "priority_value": 5,
        "default_daily_use": 1.0,
        "cold_sensitivity": 1.5,
    },
    {
        "name": "Portable Gas Generator (3KW)",
        "category": "Batteries/Power",
        "unit": "Units",
        "weight_kg_per_unit": 45.0,
        "volume_m3_per_unit": 0.35,
        "priority": "High",
        "priority_value": 50,
        "default_daily_use": 0.01,
        "cold_sensitivity": 1.4,
    },
]
